spring:
  profile:
    active: dev
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST}/${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: create-drop

      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
      show-sql: true
      format-sql: false
      defer-database-initialization: true

    slq:
      init.mode: always

    spring-doc:
      swagger-ui:
        try-it-out-enable: true
        operations-sorter: method
        tags-sorter: alpha
        filter: true